common: &common_settings
    application_name: template
    perform_authentication: true

development:
    <<: *common_settings

test:
    <<: *common_settings
    perform_authentication: false

production:
    <<: *common_settings

staging:
    <<: *common_settings