common: &common_settings
    application_name: template
    perform_authentication: true
    consecutive_failed_logins_limit: 50

development:
    <<: *common_settings

test:
    <<: *common_settings
    perform_authentication: true

production:
    <<: *common_settings

staging:
    <<: *common_settings